platform :ios, '9.0'
inhibit_all_warnings!
target 'KBLibrary_Example' do
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'AvoidCrash'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
